#This is an experimental Makefile

COMPONENT=RouterNodeC

CLEAN_EXTRA = *.nc~ *.h~ 


INCLUDES= -I..       \
          -I../Mobility
                  
CFLAGS += $(INCLUDES)


#CFLAGS += -I$(Routers)/../Mobility/MobilityC



include $(MAKERULES)


