/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'FilterMsg'
 * message type.
 */

public class FilterMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 5;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 20;

    /** Create a new FilterMsg of size 5. */
    public FilterMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new FilterMsg of the given data_length. */
    public FilterMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new FilterMsg with the given data_length
     * and base offset.
     */
    public FilterMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new FilterMsg using the given byte array
     * as backing store.
     */
    public FilterMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new FilterMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public FilterMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new FilterMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public FilterMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new FilterMsg embedded in the given message
     * at the given base offset.
     */
    public FilterMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new FilterMsg embedded in the given message
     * at the given base offset and length.
     */
    public FilterMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <FilterMsg> \n";
      try {
        s += "  [src_addr=0x"+Long.toHexString(get_src_addr())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [dst_addr=0x"+Long.toHexString(get_dst_addr())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [val=0x"+Long.toHexString(get_val())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: src_addr
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'src_addr' is signed (false).
     */
    public static boolean isSigned_src_addr() {
        return false;
    }

    /**
     * Return whether the field 'src_addr' is an array (false).
     */
    public static boolean isArray_src_addr() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'src_addr'
     */
    public static int offset_src_addr() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'src_addr'
     */
    public static int offsetBits_src_addr() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'src_addr'
     */
    public int get_src_addr() {
        return (int)getUIntBEElement(offsetBits_src_addr(), 16);
    }

    /**
     * Set the value of the field 'src_addr'
     */
    public void set_src_addr(int value) {
        setUIntBEElement(offsetBits_src_addr(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'src_addr'
     */
    public static int size_src_addr() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'src_addr'
     */
    public static int sizeBits_src_addr() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: dst_addr
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'dst_addr' is signed (false).
     */
    public static boolean isSigned_dst_addr() {
        return false;
    }

    /**
     * Return whether the field 'dst_addr' is an array (false).
     */
    public static boolean isArray_dst_addr() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'dst_addr'
     */
    public static int offset_dst_addr() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'dst_addr'
     */
    public static int offsetBits_dst_addr() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'dst_addr'
     */
    public int get_dst_addr() {
        return (int)getUIntBEElement(offsetBits_dst_addr(), 16);
    }

    /**
     * Set the value of the field 'dst_addr'
     */
    public void set_dst_addr(int value) {
        setUIntBEElement(offsetBits_dst_addr(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'dst_addr'
     */
    public static int size_dst_addr() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'dst_addr'
     */
    public static int sizeBits_dst_addr() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: val
    //   Field type: short, unsigned
    //   Offset (bits): 32
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'val' is signed (false).
     */
    public static boolean isSigned_val() {
        return false;
    }

    /**
     * Return whether the field 'val' is an array (false).
     */
    public static boolean isArray_val() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'val'
     */
    public static int offset_val() {
        return (32 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'val'
     */
    public static int offsetBits_val() {
        return 32;
    }

    /**
     * Return the value (as a short) of the field 'val'
     */
    public short get_val() {
        return (short)getUIntBEElement(offsetBits_val(), 8);
    }

    /**
     * Set the value of the field 'val'
     */
    public void set_val(short value) {
        setUIntBEElement(offsetBits_val(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'val'
     */
    public static int size_val() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'val'
     */
    public static int sizeBits_val() {
        return 8;
    }

}
